# Final Wrap-Up Index

보고서형 최종 notebook 진입점입니다. 아래 표는 실제 데이터 소스 기준 인벤토리이며,
각 task notebook은 `Setup -> Load -> Normalize -> Summary Table -> Main Figures -> Secondary Figures -> Export -> Notes`
순서를 따릅니다.

- `01_time_series_wrapup.ipynb`
- `02_classification_wrapup.ipynb`
- `03_operator_wrapup.ipynb`

In [1]:
from pathlib import Path
import sys

def find_repo_root(start: Path) -> Path:
    for candidate in [start, *start.parents]:
        if (candidate / ".git").exists() and (candidate / "notebook").exists():
            return candidate
    raise FileNotFoundError("Could not locate the repository root from the current working directory.")

REPO_ROOT = find_repo_root(Path.cwd().resolve())
NOTEBOOK_ROOT = REPO_ROOT / "notebook" / "FINAL_WRAPUP"
if str(NOTEBOOK_ROOT) not in sys.path:
    sys.path.insert(0, str(NOTEBOOK_ROOT))

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from IPython.display import Markdown, display

from _shared.io import load_curve_file, load_epoch_metrics, load_pks_results, load_run_tree
from _shared.plotting import (
    DATASET_ORDER,
    METHOD_COLORS,
    METHOD_ORDER,
    apply_report_style,
    pretty_dataset,
    pretty_method,
    pretty_model,
    pretty_pair,
    save_figure,
    save_table,
)

apply_report_style()
pd.set_option("display.max_columns", 60)
pd.set_option("display.width", 180)

NOTEBOOK_ROOT

PosixPath('/home/namkyeong/ssmo/notebook/FINAL_WRAPUP')

## Load

PKS 결과와 내 실험 결과 루트를 확인하고, notebook별 예상 row/file 개수를 표로 정리합니다.

In [2]:
PKS_ROOT = REPO_ROOT / "notebook" / "results_from_pks" / "result_zip"
TIME_SERIES_ROOT = REPO_ROOT / "results" / "paper_rerun_canonical" / "time_series" / "time_series"

inventory_rows = []

pks = load_pks_results(PKS_ROOT)
inventory_rows.append({
    "source": "PKS classification",
    "expected_artifacts": 15,
    "observed_artifacts": pks.loc[pks["task"] == "classification", "source_path"].nunique(),
    "root": str(PKS_ROOT),
})
inventory_rows.append({
    "source": "PKS operator",
    "expected_artifacts": 18,
    "observed_artifacts": pks.loc[pks["task"] == "operator", "source_path"].nunique(),
    "root": str(PKS_ROOT),
})

time_series = load_run_tree(TIME_SERIES_ROOT)
inventory_rows.append({
    "source": "Time-series summary.json",
    "expected_artifacts": 36,
    "observed_artifacts": len(time_series),
    "root": str(TIME_SERIES_ROOT),
})

inventory = pd.DataFrame(inventory_rows)
display(inventory)
inventory

                     source  expected_artifacts  observed_artifacts                                               root
0        PKS classification                  15                  15  /home/namkyeong/ssmo/notebook/results_from_pks...
1              PKS operator                  18                  18  /home/namkyeong/ssmo/notebook/results_from_pks...
2  Time-series summary.json                  36                  36  /home/namkyeong/ssmo/results/paper_rerun_canon...

                     source  expected_artifacts  observed_artifacts                                               root
0        PKS classification                  15                  15  /home/namkyeong/ssmo/notebook/results_from_pks...
1              PKS operator                  18                  18  /home/namkyeong/ssmo/notebook/results_from_pks...
2  Time-series summary.json                  36                  36  /home/namkyeong/ssmo/results/paper_rerun_canon...

## Export

In [3]:
export_path = save_table(inventory, "index", "source_inventory")
display(Markdown(f"Saved inventory table to `{export_path}`."))

Saved inventory table to `/home/namkyeong/ssmo/notebook/FINAL_WRAPUP/tables/index/source_inventory.csv`.

## Notes

- `navierstokes` PKS 폴더는 현재 비어 있으므로 operator wrap-up에서 unavailable 상태를 명시합니다.
- time-series는 `results/paper_rerun_canonical/time_series/time_series`만 공식 입력으로 사용합니다.